// GET USER

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_PENDING = "GET_USER_PENDING"
export const GET_USER_ERROR = "GET_USER_ERROR"

// ADD USER

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_PENDING = "ADD_USER_PENDING"
export const ADD_USER_ERROR = "ADD_USER_ERROR"

// DELETE USER

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_PENDING = "DELETE_USER_PENDING"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"

// UPDATE USER

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"



// ---------------product---------------------


// GET PRODUCT

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"

// ADD PRODUCT

export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_PENDING = "ADD_PRODUCT_PENDING"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"

// DELETE PRODUCT

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_PENDING = "DELETE_PRODUCT_PENDING"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

// UPDATE PRODUCT

export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT_PENDING"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"